# This cask is regenerated by the release workflow in gnugomez/majordomo on
# every release — don't edit version/sha256 by hand.
cask "majordomo" do
  version "1.1.0"
  sha256 "06750b4773938ffd2f8f82aa8aa107d9de71de616516f489136bd7a075d4f566"

  url "https://github.com/gnugomez/majordomo/releases/download/v#{version}/Majordomo-macos-arm64.dmg"
  name "Majordomo"
  desc "Menu-bar inbox for GitHub and GitLab notifications"
  homepage "https://github.com/gnugomez/majordomo"

  depends_on macos: :tahoe
  depends_on arch: :arm64

  app "Majordomo.app"

  zap trash: [
    "~/Library/Application Support/Majordomo",
    "~/Library/Preferences/dev.majordomo.app.plist",
  ]

  caveats <<~EOS
    Majordomo is not notarized. To pass Gatekeeper, either allow it under
    System Settings → Privacy & Security after the first launch attempt,
    or clear the quarantine flag:
      xattr -dr com.apple.quarantine /Applications/Majordomo.app
  EOS
end
