# This cask is regenerated by the release workflow in gnugomez/majordomo on
# every release — don't edit version/sha256 by hand.
cask "majordomo" do
  version "1.0.0"
  sha256 "3768b2d07a88bea8bccc3f84e24e1e2f6a130fc76f7c3e5633112fd81cd8a043"

  url "https://github.com/gnugomez/majordomo/releases/download/v#{version}/Majordomo-macos-arm64.dmg"
  name "Majordomo"
  desc "Menu-bar inbox for GitHub and GitLab notifications"
  homepage "https://github.com/gnugomez/majordomo"

  depends_on macos: :tahoe
  depends_on arch: :arm64

  app "Majordomo.app"

  zap trash: [
    "~/Library/Application Support/Majordomo",
    "~/Library/Preferences/dev.majordomo.app.plist",
  ]

  caveats <<~EOS
    Majordomo is not notarized: install with --no-quarantine, or allow it
    under System Settings → Privacy & Security after the first launch.
  EOS
end
